### ISSUE TITLE
[BUG] Download does not progress normally on WSL

### ISSUE THREAD

**Issue by PolarBean** [brainglobe/brainglobe-atlasapi#334] opened 2024-07-31 17:07 UTC
When running the demonstration code in the instructions i get shown a progress bar that fills out far slower than would be expected given the reported internet speed. The estimate says 2 minutes however in reality its taking 30 minutes to an hour. I have tried this on two machines both running windows subsystem for linux (WSL). both times I've started from a clean installation running  
```
brainglobe-space-1.0.2 
brainglobe_atlasapi-2.0.7
```
which i get from  
```
pip install brainglobe_atlasapi
```
even stranger is if i kill the kernel and restart after it has been running for 5 minutes (and is at 3%), it then works and is able to display the reference and annotation normally. 

See below for replication. 

```python
from brainglobe_atlasapi.bg_atlas import BrainGlobeAtlas
atlas = BrainGlobeAtlas("allen_mouse_25um")
```

![image](https://github.com/user-attachments/assets/0055882f-4fca-49f9-b500-bd73097d0d43)

**Comment by adamltyson** [comment] 2024-08-01 06:58
thanks @PolarBean I've also noticed this. Not exactly sure what the issue is, but I hope that [moving to pooch to download data](https://github.com/brainglobe/brainglobe-atlasapi/issues/284) should fix this. Not sure when we'll be able to get to it though.

**Closed** 2024-08-28 09:41 UTC
Labels: bug
