### ISSUE TITLE
[Feature] Use pooch to handle atlas downloading

### ISSUE THREAD

**Issue by viktorpm** [brainglobe/brainglobe-atlasapi#323] opened 2024-07-11 15:19 UTC
**Is your feature request related to a problem? Please describe.**

This is part of the effort to standardise atlas packaging scripts. 

**Describe the solution you'd like**

Replace inconsistent solutions to download and uncompress atlas files with pooch.

**Comment by adamltyson** [comment] 2024-08-01 06:57
Closing as duplicate of https://github.com/brainglobe/brainglobe-atlasapi/issues/284

**Closed by adamltyson** 2024-08-01 06:57 UTC
Labels: enhancement
