### ISSUE TITLE
[BUG] 'brainglobe' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by lacan** [brainglobe/brainglobe-atlasapi#408] opened 2024-09-09 15:23 UTC
**Describe the bug**
When installing brainreg via conda
```
conda install -c conda-forge brainreg
```
and following the instructions to get `brainglobe-api`
```
pip install brainglobe-atlasapi
```

Running a command `brainglobe` yeilds
```
'brainglobe' is not recognized as an internal or external command,
operable program or batch fil
```
**To Reproduce**
As described above

**Expected behaviour**
`brainglobe` to be recognised as as executable

**Computer used (please complete the following information):**

- OS: Win11
- Miniforge : mamba 1.1.0, conda 22.9.

**Comment by adamltyson** [comment] 2024-09-09 15:54
Hi @lacan,

Weird, I can't reproduce this (although I'm not on Windows). Are you definitely running `brainglobe` in the same environment as `brainglobe-atlasapi` was installed into?

PS. you shouldn't need to install the API separately, it's a dependency of `brainreg`.

**Comment by lacan** [comment] 2024-09-10 06:04
Thanks for getting back to me
Here is the conda list command
```
# packages in environment at D:\conda\conda-envs\brainreg2:
#
# Name                    Version                   Build  Channel
_libavif_api              1.1.1                h57928b3_1    conda-forge
aiohappyeyeballs          2.4.0              pyhd8ed1ab_0    conda-forge
aiohttp                   3.10.5          py311he736701_0    conda-forge
aiosignal                 1.3.1              pyhd8ed1ab_0    conda-forge
alabaster                 1.0.0              pyhd8ed1ab_0    conda-forge
annotated-types           0.7.0              pyhd8ed1ab_0    conda-forge
aom                       3.9.1                he0c23c2_0    conda-forge
app-model                 0.2.8              pyhd8ed1ab_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
asciitree                 0.3.3                      py_2    conda-forge
asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
attrs                     24.2.0             pyh71513ae_0    conda-forge
aws-c-auth                0.7.29               h5dd0cea_0    conda-forge
aws-c-cal                 0.7.4                ha1e9ad3_0    conda-forge
aws-c-common              0.9.27               h2466b09_0    conda-forge
aws-c-compression         0.2.19               ha1e9ad3_0    conda-forge
aws-c-event-stream        0.4.3                hf2a634e_0    conda-forge
aws-c-http                0.8.8                h8ce653d_1    conda-forge
aws-c-io                  0.14.18              hf17f6a9_8    conda-forge
aws-c-mqtt                0.10.4              hc4c7fd1_18    conda-forge
aws-c-s3                  0.6.5                h7c1087a_1    conda-forge
aws-c-sdkutils            0.1.19               ha1e9ad3_2    conda-forge
aws-checksums             0.1.18              ha1e9ad3_10    conda-forge
aws-crt-cpp               0.28.2               h3df387f_3    conda-forge
aws-sdk-cpp               1.11.379             ha8aa73b_8    conda-forge
babel                     2.14.0             pyhd8ed1ab_0    conda-forge
blosc                     1.21.6               h85f69ea_0    conda-forge
bokeh                     3.5.2              pyhd8ed1ab_0    conda-forge
brainglobe-atlasapi       2.0.9              pyhd8ed1ab_0    conda-forge
brainglobe-napari-io      0.3.4              pyhd8ed1ab_0    conda-forge
brainglobe-segmentation   1.2.4              pyh9208f05_0    conda-forge
brainglobe-space          1.0.2              pyhd8ed1ab_0    conda-forge
brainglobe-utils          0.5.0              pyhd8ed1ab_0    conda-forge
brainreg                  1.0.10             pyhd8ed1ab_0    conda-forge
brotli-python             1.1.0           py311hda3d55a_2    conda-forge
bzip2                     1.0.8                h2466b09_7    conda-forge
c-ares                    1.33.1               h2466b09_0    conda-forge
c-blosc2                  2.15.1               hb461149_0    conda-forge
ca-certificates           2024.8.30            h56e8100_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cachey                    0.2.1              pyh9f0ad1d_0    conda-forge
cairo                     1.18.0               h91e5215_2    conda-forge
certifi                   2024.8.30          pyhd8ed1ab_0    conda-forge
cffi                      1.17.1          py311he736701_0    conda-forge
cftime                    1.6.4           py311h0a17f05_1    conda-forge
charls                    2.4.2                h1537add_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
click                     8.1.7           win_pyh7428d3b_0    conda-forge
cloudpickle               3.0.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.2.2              pyhd8ed1ab_0    conda-forge
configobj                 5.0.8              pyhd8ed1ab_0    conda-forge
contourpy                 1.3.0           py311h3257749_1    conda-forge
cytoolz                   0.12.3          py311ha68e1ae_0    conda-forge
dask                      2024.8.2           pyhd8ed1ab_0    conda-forge
dask-core                 2024.8.2           pyhd8ed1ab_0    conda-forge
dask-expr                 1.1.13             pyhd8ed1ab_0    conda-forge
dav1d                     1.2.1                hcfcfb64_0    conda-forge
debugpy                   1.8.5           py311hda3d55a_1    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
distributed               2024.8.2           pyhd8ed1ab_0    conda-forge
docstring_parser          0.16               pyhd8ed1ab_0    conda-forge
docutils                  0.21.2             pyhd8ed1ab_0    conda-forge
double-conversion         3.3.0                h63175ca_0    conda-forge
eigen                     3.4.0                h91493d7_0    conda-forge
exceptiongroup            1.2.2              pyhd8ed1ab_0    conda-forge
executing                 2.1.0              pyhd8ed1ab_0    conda-forge
expat                     2.6.3                he0c23c2_0    conda-forge
fancylog                  0.4.2              pyhd8ed1ab_1    conda-forge
fasteners                 0.17.3             pyhd8ed1ab_0    conda-forge
ffmpeg                    6.1.2           gpl_h9cf63cc_102    conda-forge
flexcache                 0.3                pyhd8ed1ab_0    conda-forge
flexparser                0.3.1              pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_2    conda-forge
fontconfig                2.14.2               hbde0cde_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.12.1               hdaf720e_2    conda-forge
freetype-py               2.5.1              pyhd8ed1ab_0    conda-forge
frozenlist                1.4.1           py311he736701_1    conda-forge
fsspec                    2024.9.0           pyhff2d567_0    conda-forge
giflib                    5.2.2                h64bf75a_0    conda-forge
gl2ps                     1.4.2                had7236b_1    conda-forge
glew                      2.1.0                h39d44d4_2    conda-forge
glib                      2.80.2               h0df6a38_0    conda-forge
glib-tools                2.80.2               h2f9d560_0    conda-forge
graphite2                 1.3.13            h63175ca_1003    conda-forge
gst-plugins-base          1.24.5               hb0a98b8_0    conda-forge
gstreamer                 1.24.5               h5006eae_0    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
h5py                      3.11.0          nompi_py311h67016bb_102    conda-forge
harfbuzz                  9.0.0                h81778c3_0    conda-forge
hdf4                      4.2.15               h5557f11_7    conda-forge
hdf5                      1.14.3          nompi_h2b43c12_105    conda-forge
heapdict                  1.0.1              pyhd8ed1ab_1    conda-forge
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
hsluv                     5.0.4              pyhd8ed1ab_0    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
icu                       73.2                 h63175ca_0    conda-forge
idna                      3.8                pyhd8ed1ab_0    conda-forge
imagecodecs               2024.6.1        py311h509772e_3    conda-forge
imageio                   2.35.1             pyh12aca89_0    conda-forge
imagesize                 1.4.1              pyhd8ed1ab_0    conda-forge
imio                      0.3.1              pyhd8ed1ab_0    conda-forge
importlib-metadata        8.4.0              pyha770c72_0    conda-forge
importlib_metadata        8.4.0                hd8ed1ab_0    conda-forge
importlib_resources       6.4.4              pyhd8ed1ab_0    conda-forge
in-n-out                  0.2.1              pyhd8ed1ab_0    conda-forge
intel-openmp              2024.2.1          h57928b3_1083    conda-forge
ipykernel                 6.29.5             pyh4bbf305_0    conda-forge
ipython                   8.27.0             pyh7428d3b_0    conda-forge
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.4              pyhd8ed1ab_0    conda-forge
jsoncpp                   1.9.5                h2d74725_1    conda-forge
jsonschema                4.23.0             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2023.12.1          pyhd8ed1ab_0    conda-forge
jupyter_client            8.6.2              pyhd8ed1ab_0    conda-forge
jupyter_core              5.7.2           py311h1ea47a8_0    conda-forge
jxrlib                    1.1                  hcfcfb64_3    conda-forge
kiwisolver                1.4.7           py311h3257749_0    conda-forge
krb5                      1.21.3               hdf4eb48_0    conda-forge
lazy-loader               0.4                pyhd8ed1ab_1    conda-forge
lazy_loader               0.4                pyhd8ed1ab_1    conda-forge
lcms2                     2.16                 h67d730c_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libabseil                 20240116.2      cxx17_he0c23c2_1    conda-forge
libaec                    1.1.3                h63175ca_0    conda-forge
libarrow                  17.0.0          h29daf90_13_cpu    conda-forge
libarrow-acero            17.0.0          he0c23c2_13_cpu    conda-forge
libarrow-dataset          17.0.0          he0c23c2_13_cpu    conda-forge
libarrow-substrait        17.0.0          h1f0e801_13_cpu    conda-forge
libavif16                 1.1.1                h4e96d62_1    conda-forge
libblas                   3.9.0              23_win64_mkl    conda-forge
libbrotlicommon           1.1.0                h2466b09_2    conda-forge
libbrotlidec              1.1.0                h2466b09_2    conda-forge
libbrotlienc              1.1.0                h2466b09_2    conda-forge
libcblas                  3.9.0              23_win64_mkl    conda-forge
libclang13                18.1.8          default_ha5278ca_4    conda-forge
libcrc32c                 1.1.2                h0e60522_0    conda-forge
libcurl                   8.9.1                h18fefc2_0    conda-forge
libdeflate                1.21                 h2466b09_0    conda-forge
libevent                  2.1.12               h3671451_1    conda-forge
libexpat                  2.6.3                he0c23c2_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libglib                   2.80.2               h0df6a38_0    conda-forge
libgoogle-cloud           2.28.0               h5e7cea3_0    conda-forge
libgoogle-cloud-storage   2.28.0               he5eb982_0    conda-forge
libgrpc                   1.62.2               h5273850_0    conda-forge
libhwloc                  2.11.1          default_h8125262_1000    conda-forge
libiconv                  1.17                 hcfcfb64_2    conda-forge
libintl                   0.22.5               h5728263_3    conda-forge
libintl-devel             0.22.5               h5728263_3    conda-forge
libjpeg-turbo             3.0.0                hcfcfb64_1    conda-forge
liblapack                 3.9.0              23_win64_mkl    conda-forge
libnetcdf                 4.9.2           nompi_h92078aa_114    conda-forge
libogg                    1.3.5                h2466b09_0    conda-forge
libopus                   1.3.1                h8ffe710_1    conda-forge
libparquet                17.0.0          ha915800_13_cpu    conda-forge
libpng                    1.6.43               h19919ed_0    conda-forge
libprotobuf               4.25.3               h503648d_0    conda-forge
libre2-11                 2023.09.01           hf8d8778_2    conda-forge
libsodium                 1.0.20               hc70643c_0    conda-forge
libsqlite                 3.46.1               h2466b09_0    conda-forge
libssh2                   1.11.0               h7dfc565_0    conda-forge
libtheora                 1.1.1             hc70643c_1006    conda-forge
libthrift                 0.20.0               hbe90ef8_1    conda-forge
libtiff                   4.6.0                hb151862_4    conda-forge
libutf8proc               2.8.0                h82a8f57_0    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp-base              1.4.0                hcfcfb64_0    conda-forge
libxcb                    1.16                 h013a479_1    conda-forge
libxml2                   2.12.7               h0f24e4e_4    conda-forge
libzip                    1.10.1               h1d365fa_3    conda-forge
libzlib                   1.3.1                h2466b09_1    conda-forge
libzopfli                 1.0.3                h0e60522_0    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
loguru                    0.7.2           py311h1ea47a8_2    conda-forge
lz4                       4.3.3           py311h8b5e962_1    conda-forge
lz4-c                     1.9.4                hcfcfb64_0    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
magicgui                  0.8.3              pyhd8ed1ab_0    conda-forge
markdown-it-py            3.0.0              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.5           py311he736701_1    conda-forge
matplotlib-inline         0.1.7              pyhd8ed1ab_0    conda-forge
mdurl                     0.1.2              pyhd8ed1ab_0    conda-forge
meshio                    5.3.5              pyhd8ed1ab_0    conda-forge
mkl                       2024.1.0           h66d3029_694    conda-forge
msgpack-python            1.0.8           py311h3257749_1    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
multidict                 6.0.5           py311he736701_1    conda-forge
napari                    0.5.0              pyh9208f05_1    conda-forge
napari-console            0.0.9              pyh9208f05_0    conda-forge
napari-plugin-engine      0.2.0              pyhd8ed1ab_2    conda-forge
napari-svg                0.2.0              pyhd8ed1ab_0    conda-forge
natsort                   8.4.0              pyhd8ed1ab_0    conda-forge
nest-asyncio              1.6.0              pyhd8ed1ab_0    conda-forge
netcdf4                   1.7.1           nompi_py311hbdc12eb_102    conda-forge
networkx                  3.3                pyhd8ed1ab_1    conda-forge
nibabel                   5.2.1              pyha770c72_0    conda-forge
niftyreg                  1.5.69.6             he9b7a49_1    conda-forge
nlohmann_json             3.11.3               he0c23c2_1    conda-forge
npe2                      0.7.7              pyhd8ed1ab_0    conda-forge
nptyping                  2.5.0              pyhd8ed1ab_0    conda-forge
numcodecs                 0.13.0          py311hcf9f919_0    conda-forge
numpy                     1.26.4          py311h0b4df5a_0    conda-forge
numpydoc                  1.8.0              pyhd8ed1ab_0    conda-forge
openh264                  2.4.1                h63175ca_0    conda-forge
openjpeg                  2.5.2                h3d672ee_0    conda-forge
openssl                   3.3.2                h2466b09_0    conda-forge
orc                       2.0.2                h784c2ca_0    conda-forge
packaging                 24.1               pyhd8ed1ab_0    conda-forge
pandas                    2.2.2           py311hcf9f919_1    conda-forge
parso                     0.8.4              pyhd8ed1ab_0    conda-forge
partd                     1.4.2              pyhd8ed1ab_0    conda-forge
pcre2                     10.43                h17e33f8_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    10.4.0          py311h5592be9_0    conda-forge
pint                      0.24.3             pyhd8ed1ab_0    conda-forge
pip                       24.2               pyh8b19718_1    conda-forge
pixman                    0.43.4               h63175ca_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_1    conda-forge
platformdirs              4.3.2              pyhd8ed1ab_0    conda-forge
ply                       3.11               pyhd8ed1ab_2    conda-forge
pooch                     1.8.2              pyhd8ed1ab_0    conda-forge
proj                      9.4.1                hd9569ee_1    conda-forge
prompt-toolkit            3.0.47             pyha770c72_0    conda-forge
psutil                    6.0.0           py311he736701_1    conda-forge
psygnal                   0.11.1             pyhd8ed1ab_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
pugixml                   1.14                 h63175ca_0    conda-forge
pure_eval                 0.2.3              pyhd8ed1ab_0    conda-forge
pyarrow                   17.0.0          py311h06a5be4_1    conda-forge
pyarrow-core              17.0.0          py311hdea38fa_1_cpu    conda-forge
pyarrow-hotfix            0.6                pyhd8ed1ab_0    conda-forge
pyconify                  0.1.6              pyhd8ed1ab_0    conda-forge
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pydantic                  2.8.2              pyhd8ed1ab_0    conda-forge
pydantic-compat           0.1.2              pyhd8ed1ab_0    conda-forge
pydantic-core             2.20.1          py311h533ab2d_0    conda-forge
pygments                  2.18.0             pyhd8ed1ab_0    conda-forge
pynrrd                    1.0.0              pyhc1e730c_0    conda-forge
pyopengl                  3.1.6              pyhd8ed1ab_1    conda-forge
pyproject_hooks           1.1.0              pyhd8ed1ab_0    conda-forge
pyqt                      5.15.9          py311h125bc19_5    conda-forge
pyqt5-sip                 12.12.2         py311h12c1d0e_5    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
python                    3.11.9          h631f459_0_cpython    conda-forge
python-build              1.2.2              pyhd8ed1ab_0    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
python_abi                3.11                    5_cp311    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pywavelets                1.7.0           py311h0a17f05_0    conda-forge
pywin32                   306             py311h12c1d0e_2    conda-forge
pyyaml                    6.0.2           py311he736701_1    conda-forge
pyzmq                     26.2.0          py311h484c95c_2    conda-forge
qt-main                   5.15.8              h06adc49_22    conda-forge
qt6-main                  6.7.2                h913a85e_3    conda-forge
qtconsole-base            5.6.0              pyha770c72_0    conda-forge
qtpy                      2.4.1              pyhd8ed1ab_0    conda-forge
rav1e                     0.6.6                h975169c_2    conda-forge
re2                       2023.09.01           hd3b24a8_2    conda-forge
referencing               0.35.1             pyhd8ed1ab_0    conda-forge
requests                  2.32.3             pyhd8ed1ab_0    conda-forge
rich                      13.7.1             pyhd8ed1ab_0    conda-forge
rpds-py                   0.20.0          py311h533ab2d_1    conda-forge
scikit-image              0.24.0          py311hcf9f919_2    conda-forge
scipy                     1.14.1          py311hd4686c6_0    conda-forge
setuptools                73.0.1             pyhd8ed1ab_0    conda-forge
shellingham               1.5.4              pyhd8ed1ab_0    conda-forge
sip                       6.7.12          py311h12c1d0e_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
slurmio                   0.1.1              pyhd8ed1ab_0    conda-forge
snappy                    1.2.1                h23299a8_0    conda-forge
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
sphinx                    8.0.2              pyhd8ed1ab_0    conda-forge
sphinxcontrib-applehelp   2.0.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-devhelp     2.0.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-htmlhelp    2.1.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1              pyhd8ed1ab_0    conda-forge
sphinxcontrib-qthelp      2.0.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-serializinghtml 1.1.10             pyhd8ed1ab_0    conda-forge
sqlite                    3.46.1               h2466b09_0    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
superqt                   0.6.7              pyh9208f05_0    conda-forge
svt-av1                   2.2.1                he0c23c2_0    conda-forge
tabulate                  0.9.0              pyhd8ed1ab_1    conda-forge
tbb                       2021.13.0            hc790b64_0    conda-forge
tbb-devel                 2021.13.0            h053bfa6_0    conda-forge
tblib                     3.0.0              pyhd8ed1ab_0    conda-forge
tifffile                  2024.8.30          pyhd8ed1ab_0    conda-forge
tk                        8.6.13               h5226925_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tomli-w                   1.0.0              pyhd8ed1ab_0    conda-forge
toolz                     0.12.1             pyhd8ed1ab_0    conda-forge
tornado                   6.4.1           py311he736701_1    conda-forge
tqdm                      4.66.5             pyhd8ed1ab_0    conda-forge
traitlets                 5.14.3             pyhd8ed1ab_0    conda-forge
treelib                   1.7.0              pyhd8ed1ab_0    conda-forge
typer                     0.12.5             pyhd8ed1ab_0    conda-forge
typer-slim                0.12.5             pyhd8ed1ab_0    conda-forge
typer-slim-standard       0.12.5               hd8ed1ab_0    conda-forge
typing-extensions         4.12.2               hd8ed1ab_0    conda-forge
typing_extensions         4.12.2             pyha770c72_0    conda-forge
typish                    1.9.3              pyhd8ed1ab_0    conda-forge
tzdata                    2024a                h8827d51_1    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
urllib3                   2.2.2              pyhd8ed1ab_1    conda-forge
utfcpp                    4.0.5                h57928b3_0    conda-forge
vc                        14.3                h8a93ad2_20    conda-forge
vc14_runtime              14.40.33810         hcc2c482_20    conda-forge
vispy                     0.14.3          py311h0a17f05_1    conda-forge
vs2015_runtime            14.40.33810         h3bf8584_20    conda-forge
vtk                       9.3.1           qt_py311h31e1f40_205    conda-forge
vtk-base                  9.3.1           qt_py311h865aaba_205    conda-forge
wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
win32_setctime            1.1.0              pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
wrapt                     1.16.0          py311he736701_1    conda-forge
wslink                    2.1.2              pyhd8ed1ab_0    conda-forge
x264                      1!164.3095           h8ffe710_2    conda-forge
x265                      3.5                  h2d74725_3    conda-forge
xorg-libxau               1.0.11               hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xyzservices               2024.9.0           pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
yarl                      1.11.0          py311he736701_0    conda-forge
zarr                      2.18.3             pyhd8ed1ab_0    conda-forge
zeromq                    4.3.5                he1f189c_5    conda-forge
zfp                       1.0.1                he0c23c2_1    conda-forge
zict                      3.0.0              pyhd8ed1ab_0    conda-forge
zipp                      3.20.1             pyhd8ed1ab_0    conda-forge
zlib                      1.3.1                h2466b09_1    conda-forge
zlib-ng                   2.2.1                he0c23c2_0    conda-forge
zstandard                 0.23.0          py311h53056dc_1    conda-forge
zstd                      1.5.6                h0ea2cb4_0    conda-forge
```

Of note, 
- I tried here to install this environment with Python 3.11, to see if it was causing the issue (I had the same issue with Python 3.10)
- With Python 3.11, it installs Numpy 2.0, so I had to downgrade it with `conda install "numpy<2.0" `
- Because this is a shared computer, we install conda packages to a separate drive by setting the environment variables `CONDA_ENVS_DIRS` and `CONDA_PKGS_DIRS`
- This installation used to work on Windows with `brainglobe-atlasapi` versions before 2.0.6

**Comment by lacan** [comment] 2024-09-10 10:44
Yes it does! Just tested this

**Comment by adamltyson** [comment] 2024-09-11 09:29
Hi again @lacan. I can't reproduce this, whenever I install `brainglobe-atlasapi` via either pip or conda, the `brainglobe` command works. I've also [added a test for this in the conda build script](https://github.com/conda-forge/brainglobe-atlasapi-feedstock/pull/10) which passes. 

Is it possible that your shared conda config is causing some issues? 

I'm going to close the issue because I can't reproduce, and it doesn't seem to be anything to do with the atlas API package. I may be wrong though, and if you find any more information, please feel free to comment or re-open this issue.

**Closed by adamltyson** 2024-09-11 09:29 UTC
Labels: bug

**Comment by lacan** [comment] 2024-09-13 13:03
Thanks for looking into it. I will keep using `pip` and will see sporadically on windows if the issue gets magically fixed at some point.
